name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GTest
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/googletest/googletest
        sudo mkdir build
        cd build
        sudo cmake ..
        sudo make
        ls -lh lib
        sudo cp lib/libgtest* /usr/local/lib/
    - name: Install Crypto++
      run: |
        curl -O https://abumq.github.io/downloads/cryptocpp.tar.gz
        tar xf cryptocpp.tar.gz
        cd cryptopp-CRYPTOPP_5_6_5
        curl -O https://abumq.github.io/downloads/pem_pack.zip
        unzip pem_pack.zip
        cmake .
        make
        sudo make install
    - uses: actions/checkout@v3
    - name: Run CMake
      run: |
        mkdir build
        cd build
        cmake -Dtest=ON ..
    - name: make
      run: make
    - name: Run tests
      run: ./ripe-unit-tests
